CREATE DATABASE IF NOT EXISTS db_memory_game_bl;

USE db_memory_game_bl;

CREATE TABLE IF NOT EXISTS Player (

	id INT AUTO_INCREMENT UNIQUE PRIMARY KEY,

	cpf VARCHAR(14) UNIQUE NOT NULL,
	usuario VARCHAR(25) UNIQUE NOT NULL,
	senha VARCHAR(32) NOT NULL,

	recorde TIME DEFAULT NULL,

	ativo BOOL DEFAULT TRUE

);

DESC Player;